### ISSUE TITLE
Add the Map component 

### ISSUE THREAD

**Issue by MAVRICK-1** [SHANKARA-CODERS/e-commerce_website#16]
A the Map component
https://github.com/SHANKARA-CODERS/e-commerce_website/tree/main/src/components/map

<img width="959" alt="Screenshot 2024-02-05 180557" src="https://github.com/SHANKARA-CODERS/e-commerce_website/assets/146999057/9f1c5523-a943-47ea-90f5-97db657bda37">

place the Map component trhe yellow part and it must be responsive
you can make changes in map.css  file part.

https://github.com/SHANKARA-CODERS/e-commerce_website/blob/main/src/App.js#L164
make the changes in above routting part

@Animesh239

**Comment by Animesh239** [comment]
What the map show,
The location of all products or the filtered products ???

**Comment by MAVRICK-1** [comment]
Location of the nearest filtered products

**Comment by MAVRICK-1** [comment]
close by #19

**Comment by MAVRICK-1** [comment]
close by #19
