### ISSUE TITLE
Problem with Routing Path

### ISSUE THREAD

**Issue by MAVRICK-1** [SHANKARA-CODERS/e-commerce_website#17]
**Describe the bug**
There is an issue with the routing path. Currently, when products are listed, the path appears as '/cat/groceries/dal-and-pulses', which corresponds to the category of the product. However, when clicking on an item, the routing changes to 'product/2', which leads to the wrong page. 

Our main objective is to update the routing path to '/cat/groceries/dal-and-pulses/1', where '1' represents the product ID of 'dal-and-pulses'. This change is crucial because it allows us to easily track new products through their cart_item and ID when they are added to the system.
<img width="950" alt="Screenshot 2024-02-05 184750" src="https://github.com/SHANKARA-CODERS/e-commerce_website/assets/146999057/93765495-b261-4708-a513-98eb0f2e8954">

<img width="953" alt="Screenshot 2024-02-05 184904" src="https://github.com/SHANKARA-CODERS/e-commerce_website/assets/146999057/7e4bce59-19f5-407e-b318-3eb85c08b2e9">

So make the changes accordingly
https://github.com/SHANKARA-CODERS/e-commerce_website/blob/main/src/pages/Details/index.js
This dynamic routing created in the above file

change the useParams according https://github.com/SHANKARA-CODERS/e-commerce_website/blob/main/src/pages/Details/index.js#L65C30

make changes to rectify it and also add the sufficient screenshots

This is bug must be resloved

**Comment by MAVRICK-1** [comment]
@RickDeb2004  this must be solved our frontent is almost complete this is buggest bug .

**Comment by MAVRICK-1** [comment]
@RickDeb2004 code base maay kuc change hoga then you can update and start

**Comment by MAVRICK-1** [comment]
@RickDeb2004 aj ei complete kar Dena

**Comment by RickDeb2004** [comment]
are you sure we have to change this file only?

**Comment by MAVRICK-1** [comment]
We have to change the Details page. Coz in previous dataset every category items has a unique ID
But In new dataset only the subcategory products has unique ID

**Comment by MAVRICK-1** [comment]
@RickDeb2004 If u can solve it go head or we have to switch to previous dataset coz their not enough time

**Comment by MAVRICK-1** [comment]
closed by #21
